      *------------------------------------------------------------------------------
      * <auto-generated>
      *     This code was generated by a tool.
      *
      *     Changes to this file may cause incorrect behavior and will be lost if
      *     the code is regenerated.
      * </auto-generated>
      *------------------------------------------------------------------------------

       class-id MidtermProject.SiteMaster is partial
               inherits type System.Web.UI.MasterPage public.
               
       working-storage section.
       01 HeadContent type System.Web.UI.WebControls.ContentPlaceHolder protected.
       01 MasterPageScriptManager type System.Web.UI.ScriptManager protected.
       01 HeadLoginView type System.Web.UI.WebControls.LoginView protected.
       01 HeadHomeLink type System.Web.UI.HtmlControls.HtmlAnchor protected.
       01 HeadAboutLink type System.Web.UI.HtmlControls.HtmlAnchor protected.
       01 MainContent type System.Web.UI.WebControls.ContentPlaceHolder protected.
              
       end class.
    