      *------------------------------------------------------------------------------
      * <auto-generated>
      *     This code was generated by a tool.
      *
      *     Changes to this file may cause incorrect behavior and will be lost if
      *     the code is regenerated.
      * </auto-generated>
      *------------------------------------------------------------------------------

       class-id MidtermProject.Account.ChangePasswordSuccess is partial
               inherits type System.Web.UI.Page public.
               
       working-storage section.
              
       end class.
       