      *------------------------------------------------------------------------------
      * <auto-generated>
      *     This code was generated by a tool.
      *
      *     Changes to this file may cause incorrect behavior and will be lost if
      *     the code is regenerated.
      * </auto-generated>
      *------------------------------------------------------------------------------

       class-id MidtermProject.Account.Login is partial
               inherits type System.Web.UI.Page public.
               
       working-storage section.
       01 RegisterHyperLink type System.Web.UI.WebControls.HyperLink protected.
       01 LoginUser type System.Web.UI.WebControls.Login protected.
       
       end class.