	  *------------------------------------------------------------------------------
      * <auto-generated>
      *     This code was generated by a tool.
      *
      *     Changes to this file may cause incorrect behavior and will be lost if
      *     the code is regenerated.
      * </auto-generated>
      *------------------------------------------------------------------------------

       class-id MidtermProject.Account.Register is partial
               inherits type System.Web.UI.Page public.
               
       working-storage section.
       01 RegisterUser type System.Web.UI.WebControls.CreateUserWizard protected.
       01 RegisterUserWizardStep type System.Web.UI.WebControls.CreateUserWizardStep protected.
       
       end class.
